### ISSUE TITLE
heroku-buildpack-activestorage-preview doesn't work in conjucntion with https://github.com/daetherius/heroku-buildpack-mysql

### ISSUE THREAD

**Issue by mikefsm** [heroku/heroku-buildpack-activestorage-preview#17]
With both buildpacks installed, PDF previews do not work. If I remove the https://github.com/daetherius/heroku-buildpack-mysql buildpack they work fine. But I need the MySQL buildpack.

**Comment by dzuelke** [comment]
I assume this is no longer an issue now that we're doing significantly fewer package installs.
