### ISSUE TITLE
CVEs in current ffmpeg build

### ISSUE THREAD

**Issue by schneems** [heroku/heroku-buildpack-activestorage-preview#2]
In the interest in consolidating information, I'm moving this over to GitHub issues:

Canonical does not support the ffmpeg package for Xenial, Artful or Bionic because it resides in the Universe repository. The ffmpeg in universe currently has open CVEs.

https://people.canonical.com/~ubuntu-security/cve/pkg/ffmpeg.html

**Comment by hone** [comment]
Fixed by #3.
