### ISSUE TITLE
Add testing for all stacks

### ISSUE THREAD

**Issue by edmorley** [heroku/heroku-buildpack-activestorage-preview#20]
Heroku-20 beta was just released:
https://devcenter.heroku.com/changelog-items/1937

I tried installing this buildpack on a Heroku-20 app, and the build succeeded, though I didn't test any further.

It would be great to add some per-stack testing to this buildpack, to ensure it works on Heroku-20 at runtime and to prevent future stack-specific regressions like #9).

Many thanks :-)

**Comment by edmorley** [comment]
Tracked internally at W-8276311.

**Comment by dzuelke** [comment]
Heroku-22 as well for #27 ;)

It shouldn't be hard, a matrix like https://github.com/heroku/heroku-buildpack-php/blob/5c628e7e989e9d96d742bea67f3245bebe5fc7be/.github/workflows/ci.yml#L25-L32 and pass that to `Hatchet::Runner.new`.
