### ISSUE TITLE
Not working on fresh Rails 6.1 app

### ISSUE THREAD

**Issue by Bodacious** [heroku/heroku-buildpack-activestorage-preview#23]
Hi all,

Firstly, I'm not sure if this buildpack is intended for use with Rails 6.0 or not? The README clearly mentions Rails 5.2, but I can't see any other reference for Rails 6 apps. The [latest Heroku support docs](https://devcenter.heroku.com/articles/active-storage-on-heroku) refer to this build pack, which is why I'm trying to use it with Rails 6.1.

When I try to deploy to Heroku a completely fresh Rails app, the deploy fails with the error below:

```
...

remote:        Installing gobject-introspection 3.4.4 with native extensions
remote:        Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
remote:
remote:        current directory:
remote:        /tmp/build_182d58a7/vendor/bundle/ruby/3.0.0/gems/atk-3.4.4/dependency-check
remote:        /tmp/build_182d58a7/vendor/ruby-3.0.1/bin/ruby
remote:        -I/tmp/build_182d58a7/vendor/ruby-3.0.1/lib/ruby/3.0.0 -rrubygems
remote:        /tmp/build_182d58a7/vendor/bundle/ruby/3.0.0/gems/rake-13.0.3/exe/rake
remote:        RUBYARCHDIR\=/tmp/build_182d58a7/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0/atk-3.4.4
remote:        RUBYLIBDIR\=/tmp/build_182d58a7/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0/atk-3.4.4
remote:        installing 'libatk1.0-dev' native package... installing 'libatk1.0-dev' native
remote:        package... require super user privilege
remote:        require super user privilege
remote:        'libatk1.0-dev' native package is required.
remote:        Run the following command as super user to install required native package:
remote:          # apt install -V -y libatk1.0-dev
remote:        'libatk1.0-dev' native package is required.
remote:        Run the following command as super user to install required native package:
remote:          # apt install -V -y libatk1.0-dev
remote:        --------------------
remote:
remote:
remote:        rake failed, exit code 1
remote:
remote:        Gem files will remain installed in
remote:        /tmp/build_182d58a7/vendor/bundle/ruby/3.0.0/gems/atk-3.4.4 for inspection.
remote:        Results logged to
remote:        /tmp/build_182d58a7/vendor/bundle/ruby/3.0.0/extensions/x86_64-linux/3.0.0/atk-3.4.4/gem_make.out
remote:
remote:        An error occurred while installing atk (3.4.4), and Bundler cannot continue.
remote:        Make sure that `gem install atk -v '3.4.4' --source 'https://rubygems.org/'`
remote:        succeeds before bundling.
remote:
remote:        In Gemfile:
remote:          gtk3 was resolved to 3.4.4, which depends on
remote:            atk
remote:
remote:  !
remote:  !     Failed to install gems via Bundler.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote:
remote:  !     Push failed
remote: Verifying deploy...
remote:
```

Relevant part of my Gemfile:

``` ruby 
# Use Active Storage variant
gem 'image_processing', '~> 1.2'

gem "poppler"

gem "gtk3"

gem "streamio-ffmpeg"

gem "atk", '~> 3.4.4'
```

On a separate app with a similar setup, I've also tried to install the apt-get build-pack and manually include the following packages—but still no luck: 

```
libgirepository-1.0-1
libgirepository1.0-dev
libpoppler-glib-dev
libatk1.0-dev
libpango1.0-dev
libharfbuzz-dev
libcairo2-dev
```

Can someone please provide some guidance on how to get ActiveStorage PDF and video previews working on Heroku?

**Comment by iiewad** [comment]
Just `gem "image_processing"` can work,  remove the `gem "poppler"`

**Comment by diegollams** [comment]
Is there a solution for this?

**Comment by jrochkind** [comment]
Hi, I'm just a fellow user, not a maintainer at all. But this buildpack definitely works fine with Rails 6.1, I use it with that, that's not the issue. 

I don't believe the error you are reporting is related to this buildpack? 

The error says on app deploy it could not install the gem `gobject-introspection`.  I am not sure where that gem comes from or why it is in your app. What led you to think the error was related to this buildpack?

**Comment by dzuelke** [comment]
This buildpack only provides binaries of `ffmpeg` and Popplers various `pdfto…` programs for Rails to shell out to for Rails' ActiveStorage Preview feature.

It does not provide headers for `libpoppler`, or any of the GTK libraries used by the `gtk3` and related Gems.
