### ISSUE TITLE
ffmpeg/ffprobe on heroku-22 will segfault with URL arguments

### ISSUE THREAD

**Issue by jrochkind** [heroku/heroku-buildpack-activestorage-preview#27]
Hi, my app uses this buildpack to get ffmpeg/ffprobe installed, for use with Rails.  

But then the app also calls ffmpeg and ffprobe directly for it's own uses, not just the way Rails calls it. 

On heroku-22 stack, some calls to ffmpeg or ffprobe as installed by this app will result in a segfault. 

In particular, ffmpeg and ffprobe both have a feature where they can be called with a URL argument for remote input, not just a local filesystem argument.  This is especially useful for ffprobe, as it does not need to download the whole file to probe it, it'll just download the prefix it needs.  Eg:

    ffprobe https://scih-data-dev.s3.amazonaws.com/test_video/SampleVideo_360x240_1mb.mp4

    ffmpeg -i https://scih-data-dev.s3.amazonaws.com/test_video/SampleVideo_360x240_1mb.mp4 converted.ogg

On heroku-22 stack, with this buildpack, both of the above commands result in a segfault. 

On heroku-20 with this backpack, both of the above commands work fine. 

Please let me know if there is a better place to report this; also please let me know if this is considered a bug, or if since Rails itself may not currently call ffmpeg/ffprobe with a URL argument, perhaps it is not supported?

Also, if anyone knows any other way to get ffmpeg/ffprobe installed on heroku-22 other than this buildpack, please let me know!

**Comment by jrochkind** [comment]
OK, I found this alternate buildpack for installing ffmpeg:

https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git

And in fact, have the same problem under that buildpack.  

heroku-20 our sample command works fine, heroku-22 we get a segfault. 

So this may actually be a heroku-22 problem of some kind? 

It still is a problem for people trying to use ffmpeg on heroku-22. 

I guess I'll try filing it via usual heroku support channel.

**Comment by schneems** [comment]
For anyone who is experiencing this issue, please try out the instructions on this PR to confirm that it is working as expected. Sorry about the wait. https://github.com/heroku/heroku-buildpack-activestorage-preview/pull/31
