### ISSUE TITLE
dokku deployment fails

### ISSUE THREAD

**Issue by RailingResi** [heroku/heroku-buildpack-activestorage-preview#4]
Hi, 
I added the preview buildpack to my .buildpacks file for dokku:

> 
> https://github.com/heroku/heroku-buildpack-nodejs.git#v115
> https://github.com/heroku/heroku-buildpack-ruby.git#v173
> https://github.com/heroku/heroku-buildpack-activestorage-preview
> 

the error i am getting at the last buildpack is: 

> =====> Downloading Buildpack: https://github.com/heroku/heroku-buildpack-activestorage-preview
> =====> Detected Framework: ActiveStorage Preview
> -----> Installing binary dependencies for ActiveStorage Preview
>        Downloading packages..
>        Installing packages...
> **remote: /tmp/buildpackLX9gY/export: line 3: unexpected EOF while looking for matching `"'**

I am pretty new to all these deployment things, but for me it seems like there was an error in your compile file.  I found your docu on heroku about the preview feature for active storage PDFs and Videos. I would be really happy if you had some advice or if you could solve it. 
Thank you.

**Comment by schneems** [comment]
We don’t explicitly support dokku. If you can get this to fail on Heroku though I’ll be happy to take a look. As is I don’t even have a way to test this with dokku.

My guess is that there is a difference in bash settings maybe? @tt or @Damien you seen anything like this before? Any ideas?

**Comment by ariejan** [comment]
@RailingResi I had the same issue with Dokku. You can fix it by putting activestorage-preview on the first line, then node, then ruby. 

```
https://github.com/heroku/heroku-buildpack-activestorage-preview
https://github.com/heroku/heroku-buildpack-nodejs.git#v123
https://github.com/heroku/heroku-buildpack-ruby.git#v190
```

**Comment by SampsonCrowley** [comment]
I ran into this issue on heroku. I haven't switched buildpack index order, but It seems like it should work regardless of buildback order, since server execution doesn't start until after release phase

**Comment by SampsonCrowley** [comment]
indeed changing buildpack order did fix it on heroku. I'm still of the opinion that that is a bug worth fixing, and index order shouldn't matter for installing binaries to the system

**Comment by SampsonCrowley** [comment]
but if there is a particular reason it MUST be added as the first index, that should be added to the docs

**Comment by ariejan** [comment]
I'm no expert on buildpacks, but my guess would be that somewhere below [line 55 of `compile`](https://github.com/heroku/heroku-buildpack-activestorage-preview/blob/master/bin/compile#L55-L66) some command encounters content it didn't expect. It's very well possible that env variables have been changed by the other buildpacks - so putting this one on top resolves the issue.
