### ISSUE TITLE
unable to preview video because ffmpeg is not working on heroku-18

### ISSUE THREAD

**Issue by nicolasmlv** [heroku/heroku-buildpack-activestorage-preview#5]
So I have this app on Heroku-16 :

```
$ heroku buildpacks
=== myapp Buildpack URLs
1. https://github.com/heroku/heroku-buildpack-activestorage-preview
2. heroku/ruby

$ heroku run bash
~ $ which ffmpeg
/app/.heroku/activestorage-preview/usr/bin/ffmpeg
~ $ ffmpeg
ffmpeg version 4.0 Copyright (c) 2000-2018 the FFmpeg developers (see details)
```
<details>
<summary>ffmpeg version 4.0 details</summary>
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 20160609
  configuration: --prefix=/home/work/sffmpeg/build --datadir=/home/work/sffmpeg/build/etc --disable-shared --enable-static --enable-pic --pkg-config-flags=--static --enable-gpl --enable-version3 --disable-doc --disable-debug --disable-ffplay --disable-outdevs --enable-runtime-cpudetect --extra-cflags='-I/home/work/sffmpeg/build/include -static' --extra-ldflags=-L/home/work/sffmpeg/build/lib --extra-libs='-lstdc++ -lexpat -ldl -lm -lpthread' --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libaom --enable-libmp3lame --enable-libspeex --enable-libtheora --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libvpx --enable-libopus --enable-libfreetype --enable-libass
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
</details>

So yes, it works for heroku-16, but then I want to upgrade to Heroku-18 :

```
$ heroku stack:set heroku-18
$ git commit --allow-empty -m "Empty commit for heroku-18"
$ git push (I can see in the logs "Purging Cache. Changing stack from heroku-16 to heroku-18")
$ heroku run bash
~ $ which ffmpeg
/app/.heroku/activestorage-preview/usr/bin/ffmpeg
~ $ ffmpeg
ffmpeg: error while loading shared libraries: libxcb-shm.so.0: cannot open shared object file: No such file or directory
```

ffmpeg commands are not working, so i am unable to preview video with this repo + heroku-18 (and using ruby libs that are using ffmpeg otherwise)

**Comment by schneems** [comment]
Internal ticket link 625888

**Comment by nicolasmlv** [comment]
now working thanks to https://devcenter.heroku.com/changelog-items/1484

**Comment by ajay-ba** [comment]
> now working thanks to https://devcenter.heroku.com/changelog-items/1484

@nicolasmlv I'm using Heroku stack-18 and having this issue: "ffmpeg: error while loading shared libraries: libvpx.so.5: cannot open shared object file: No such file or directory" if you have any idea about it; please let me know.
Thanks.

**Comment by fakedevil** [comment]
Seems like the issue is on heroku libvpx5 is only available during build time and not runtime.
https://devcenter.heroku.com/articles/stack-packages
" If a cell listing a version is marked up with yellow text and background, it means that the package is available only at build time, but not at runtime."

Can we open another ticket to heroku to make it available during runtime? I see that the vpx3 is available during runtime for stack-16, so this is probably a mistake on their part.
