### ISSUE TITLE
How to add webp support?

### ISSUE THREAD

**Issue by nicolasmlv** [heroku/heroku-buildpack-activestorage-preview#6]
Could you provide a guidance on how to add support for webp or other formats?

When I run 
```
$ heroku run bash
~ $ identify -list format
```

There isn't WEBP, so when users are uploading webp files, there is an error.

My main request would be to add webp support in this buildpack. But I have seen three others format that users uploaded and that ActiveStorage failed to analyze :

`failed with error: identify: delegate failed 'dwebp'`
 `identify: no decode delegate for this image format 'JPF'`
`identify: no decode delegate for this image format 'EMF'`
`failed with error: identify: delegate failed 'ufraw-batch' `

So my second request would be some guidance on how to add a format for Active Storage on Heroku

**Comment by schneems** [comment]
This buildpack only adds preview support for PDFs and movies. Image preview support comes from imagemagick (try gem mini magick). If an image preview is not being generated correctly it should be their issue.

Are you seeing webp previews working locally?

**Comment by schneems** [comment]
Linking internal ticket ID 625851.
