### ISSUE TITLE
'Memory quota vastly exceeded' on every preview of video with resize

### ISSUE THREAD

**Issue by raphaelpra** [heroku/heroku-buildpack-activestorage-preview#7]
I am trying to generate a thumbnail for uploaded video :
`
attached.preview(resize: "200x200").processed.service_url
`
Works properly locally, but whenever I try it on heroku It crashes due to a lack of memory. I have try on a server and through the console and it failed... My video size is 80Mo (which doesn't seems that big a video to me) and I am working on standard-x1 dynos. Is there a way to generate my video's thumbnails without crashing the server ? Any workaround ?

**Comment by schneems** [comment]
Can you please open a support ticket. Go to help.heroku.com and search for
“active storage”.
