### ISSUE TITLE
Missing library for ffmpeg on Heroku-18 stack

### ISSUE THREAD

**Issue by SebouChu** [heroku/heroku-buildpack-activestorage-preview#9]
Hello!

I can't analyze videos uploaded via ActiveStorage in my Rails 5.2.3 application.

It fails when it parses the JSON output of the `ffprobe` command so I checked the installation with `ffmpeg -v` in the console, and now Heroku returns a missing library error:

```
ffmpeg: error while loading shared libraries: libaom.so.0: cannot open shared object file: No such file or directory
```

Any solution? Thanks

**Comment by NeilvB** [comment]
I've got the same problem.

I wonder if this might be related to the recent ffmpeg update d8e1e4c3fbef429b166127b8d7bf4d675ad6cd0a.

**Comment by pixeltrix** [comment]
@cji I noticed that you set `BUILD_SHARED_LIBS=1` for the aom build in heroku/sffmpeg@40963e2 - was this intentional? Seems like this could be the source of the problem.

**Comment by SebouChu** [comment]
@NeilvB You're right. I checked between two Heroku apps using the same stack (Heroku-18)

The working environment still uses ffmpeg 4.0.0-1, whereas the one with errors has the 4.2.1 update

**Comment by cji** [comment]
I've opened a PR to revert to 4.0.0-1 for now while we investigate the updated build.

**Comment by cji** [comment]
The change to use the updated ffmpeg for this buildpack has been reverted. Thank you!

**Comment by SebouChu** [comment]
Even with the updated version of the buildpack, it looks like it still uses the 4.2.1 version of ffmpeg :(

I tried the "remove-deploy-add-redeploy" method, but still the same 😢

**Comment by cji** [comment]
@SebouChu I just created a new application to test and it's showing ffmpeg 4.0. Can you please open a support ticket with Heroku?

**Comment by SebouChu** [comment]
@cji Do you know if there is some kind of cache to clear where the build phase could pick some "already downloaded" buildpacks ? I'll try to open a support ticket to Heroku when I'll find the correct place to do that 😄

**Comment by cji** [comment]
@SebouChu I'm not sure, but I found this in our help docs. Hopefully it works!

https://help.heroku.com/18PI5RSY/how-do-i-clear-the-build-cache 

You can also open a ticket from this page.

**Comment by SebouChu** [comment]
@cji You got it right!

If you want to re-create the issue on your side, that's what I did:
- Create a new app
- Deploy it
  - *At this point, ffmpeg is not installed*
- Add latest version of the buildpack
```bash
$ heroku buildpacks:add -i 1 https://github.com/heroku/heroku-buildpack-activestorage-preview
```
- Deploy
  - *As this point, ffmpeg 4.0.0-1 is installed and working properly*
- Remove buildpack and add the 4.2.1 version
```bash
$ heroku buildpacks:add -i 1 https://github.com/heroku/heroku-buildpack-activestorage-preview.git#381a6fc6d7a44e425cfe532d131aaa6947bdd4b2
```
- Deploy
  - *As this point, ffmpeg 4.2.1 is installed but not working*
- Remove buildpack and re-add the latest version
```bash
$ heroku buildpacks:add -i 1 https://github.com/heroku/heroku-buildpack-activestorage-preview
```
- Deploy
  - *Heroku gets the version from cache somehow, so ffmpeg 4.2.1 is still there*
- Clear build cache and deploy
  - *ffmpeg 4.0.0-1 is installed and working properly once again !* 🎉
